### ISSUE TITLE
How to stop autobuy?

### ISSUE THREAD

**Issue by SACRD** [dwhiffing/idle-game#1]
I have like 100 villages with 0 Lamb (game is hardly lagging)
I cant complete the quest, because i cant get lambs (all lambs going to autobuy)

**Comment by drop-dan** [comment]
I made a version that disabled autobuy to fix this issue, but I figured no one would ever play this so I never pushed it! If you're enjoying the game, I'll gladly push and continue work on it.

Thanks for the bug report! Please let me know if you have any ideas/feature requests

**Comment by SACRD** [comment]
you definitely should push this version!

**Comment by drop-dan** [comment]
I'm curious, how did you stumble upon this game?

**Comment by dwhiffing** [comment]
I'm curious, how did you stumble upon this game?

**Comment by SACRD** [comment]
Just googled "redux idle game" : D

**Comment by dwhiffing** [comment]
I've pushed the version with the auto buy toggle, let me know if you get a chance to try it
